#!/bin/bash

echo "Automated script for downloading and preparing the Miner for Bazo-blockchain"
echo "  Downloading BAZO-Miner from Github"
go get github.com/bazo-blockchain/bazo-miner
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
go build
echo "Download & build of BAZO-Miner - Finished"
echo " "

echo "Automated script for downloading and preparing GO"
echo "Setup BAZO-Client - Started"
echo "  Downloading BAZO-Client from Github"
cd 
go get github.com/bazo-blockchain/bazo-client
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
go build
cd 
echo "Setup BAZO-Client - Finished"
echo " "

echo "Creating Account for this machines Miner"
cd /home/ubuntu/BAZO-Scripts-Fabio
git pull origin
cp RootAccountWallet.txt /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
cp RootAccountWallet.txt /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
cp RootAccountCommitment.txt /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client

cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
echo this machines public ip:
pbIP=$(curl https://ipinfo.io/ip)
echo pbIP
echo enter bootstrap ip: [number]
read btIP
jq '.this_client.ip="'$pbIP'"' configuration.json > temp.json
rm configuration.json
jq '.bootstrap_server.ip="'$btIP'"' temp.json > configuration.json
echo "configuration.json"
cat configuration.json
rm temp.json
cd
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
./bazo-client account create --rootwallet RootAccountWallet.txt --wallet Wallet.txt 

echo " "
echo "Account Transaction [accTx] verified? if not restart miner: [y/n]"
read restarted
if [ "$restarted" != "n" ]
  then ./bazo-client account create --rootwallet RootAccountWallet.txt --wallet Wallet.txt 
  else echo this will crash... Better abort mission now!!!
fi
echo "new Wallet.txt created"

echo " "
echo "Please insert transaction count [txcount] for root account (same as in block mentioned): [number]"
read answer
echo transfer 2000 from RootAccount to this account.
echo ./bazo-client funds --from RootAccountWallet.txt --to Wallet.txt --txcount $answer --amount 2000 --multisig RootAccountWallet.txt
./bazo-client funds --from RootAccountWallet.txt --to Wallet.txt --txcount $answer --amount 2000 --multisig RootAccountWallet.txt

echo " "
echo "Restart Miner if Sig1 invalid error occurs."
echo Miner restarted: [y/n]
read restarted
if [ "$restarted" != "n" ]
  then ./bazo-client funds --from RootAccountWallet.txt --to Wallet.txt --txcount $answer --amount 2000 --multisig RootAccountWallet.txt
  else echo this will crash... Better abort mission now!!!
fi

echo " "
echo "Funds transaction successfully verified: [y/n]"
read restarted
if [ "$restartet" != "n" ]
  then echo "perfect :-)"
  else echo this will crash... Better abort mission now!!!
fi
echo "enable staking for new account" 
echo ./bazo-client staking enable --wallet Wallet.txt --commitment Commitment.txt
./bazo-client staking enable --wallet Wallet.txt --commitment Commitment.txt

echo " "
echo "If transaction could not be verified restart miner and insert [y]: [y/n]"
read restarted
if [ "$restartet" != "n" ]
  then ./bazo-client staking enable --wallet Wallet.txt --commitment Commitment.txt
  else echo this will crash... Better abort mission now!!!
fi
cp Wallet.txt /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
cp Commitment.txt /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
cd
echo "copy database to miner folder"
cd /home/ubuntu/BAZO-Scripts-Fabio
cp RootAccountStore.db /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner/Store.db
echo " "

echo "You can start this miner with:"
echo ./bazo-miner start --database Store.db --address echo $(curl https://ipinfo.io/ip):8000 --bootstrap $btIP:8000 --wallet Wallet.txt --commitment Commitment.txt --multisig RootAccountWallet.txt --rootwallet RootAccountWallet.txt --rootcommitment RootAccountCommitment.txt"
