#!/bin/bash

echo "Script for Downloading and preparing BAZO Client and Bazo Miner when Account is already created."
echo "Downloading the Errors Package with: go get github.com/pkg/errors"
go get github.com/pkg/errors
echo "Downloading the Client and Miner Package with: go get github.com/bazo-blockchain/bazo-client"
go get github.com/bazo-blockchain/bazo-client
cd /home/ubuntu/BAZO-Scripts-Fabio
git pull origin

echo " "
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
echo "All Branches on Miner:"
git branch -a
echo "Insert Bazo Github Branch for Miner"
read minerbranch 
echo "git checkout $minerbranch ? [y/n]"
read selection
if [ "$selection" = "y" ]
  then git checkout $minerbranch
  else exit 1
fi
go build 
echo "Miner with branch $minerbranch  built."

echo " "
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
echo "All Branches on Client:"
git branch -a
echo "Insert Bazo Github Branch for Client"
read clientbranch 
echo "git checkout $clientbranch ? [y/n]"
read selection
if [ "$selection" = "y" ]
  then git checkout $clientbranch
  else exit 1
fi
go build
echo "Client with branch $clientbranch built."

cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
pbIP=$(curl https://ipinfo.io/ip)
echo " "
echo "This machines public IP:"
echo $pbIP
echo "enter bootstrap IP: [number]"
read btIP
jq '.this_client.ip="'$pbIP'"' configuration.json > temp.json
rm configuration.json
jq '.bootstrap_server.ip="'$btIP'"' temp.json > temp2.json
jq '.multisig_server.ip="'$btIP'"' temp2.json > configuration.json
echo "configuration.json"
cat configuration.json
rm temp.json
rm temp2.json
cd /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client

echo "List of Wallets:"
cd /home/ubuntu/BAZO-Scripts-Fabio/Wallets
ls
echo " "
echo "Is there a Wallet with the name of this VM's location? [y/n]"
read selection
if [ "$selection" = "y" ]
  then cp -r /home/ubuntu/BAZO-Scripts-Fabio/Wallets /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
       cp -r /home/ubuntu/BAZO-Scripts-Fabio/Wallets /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-client
       echo "Wallet folder is successfully cpoied to the miner and client"
  else git pull origin
       echo "copy Wallet folder manually to the client and miner folder"
fi

echo " "
echo "List of Commitments:"
cd /home/ubuntu/BAZO-Scripts-Fabio/Wallets
ls
echo " "
echo "Is there a Commitment with the name of this VM's location? [y/n]"
read selection
if [ "$selection" = "y" ]
  then cp -r /home/ubuntu/BAZO-Scripts-Fabio/Wallets /home/ubuntu/go/src/github.com/bazo-blockchain/bazo-miner
       echo "Commitment folder is successfully cpoied to the miner and client"
  else git pull origin
       echo "Copy Commitment folder manually to the miner folder"
fi

echo " "
echo "Bazo Miner can be started in the Miner folder with: "
echo "./bazo-miner start --database Store.db --address $pbIP:8000 --bootstrap $btIP:8000 --wallet Wallets/Wallet---.txt --commitment Commitments/Commitment---.txt --multisig Wallets/WalletAWSLondon.txt --rootwallet Wallets/WalletAWSLondon.txt --rootcommitment Commitments/CommitmentAWSLondon.txt --confirm"
